### ISSUE TITLE
Need email contact for mixly.org to get latest versions for education project

### ISSUE THREAD

**Issue by TerryKing** [mixly/Mixly_Arduino#14]
Hello Everyone,
I am writing educational curriculum and detailed how-to for USA students.  The mixly.org site does not allow download of the latest WIN and MAC code except through a cloud server that seems inaccessable. Or perhaps my Chinese isn't good enough.  
I understand that Mixly (full name Mixly_Arduino, Chinese name Mi Siqi) is a domestic independent research and development, free and open source graphical programming under the leadership of Fu Yan, the head of the Creativity Education Laboratory of the Department of Education, Beijing Normal University. 
Can someone give me his email, or another email contact at MIXLY.ORG??
I will make all files available on my webspace at http://ArduinoInfo.Info
THANKS!   terry@terryking.us

**Comment by hznupeter** [comment]
116.62.49.166
Keep visit  our  [wiki](http://mixly.readthedocs.io)

**Comment by kufirre** [comment]
Hello, Sorry but the wiki page has a download link that does not work. See:

**Comment by kufirre** [comment]
https://mixly.readthedocs.io/zh_CN/latest/basic/01.Installation-for-Mixly.html

**Comment by hznupeter** [comment]
Thk .i've fixed it

**Comment by hznupeter** [comment]
Thk .i've fixed it
