### ISSUE TITLE
Why Russian translation crash startup Mixly?

### ISSUE THREAD

**Issue by Enio449** [mixly/Mixly_Arduino#15]
Hi!

I'm make Russian translate. And add:
blockly\msg\js\company\ru.js
blockly\msg\js\company\language\ru.js

modify in blockly\apps\mixly\code.js:
Code.LANGUAGE_NAME = {
  'zh-hans': '简体中文',
  'zh-hant': '繁體中文',
  'en': 'English',
  'ru': 'Русский',

};

Code.getLang = function() {
  var lang = Code.getStringParamFromUrl('lang', '');
  if (Code.LANGUAGE_NAME[lang] === undefined) {
    // Default to ru.
    lang = 'ru';
  }
  return lang;
};

Modify setting\config.properties:
language=ru

Modify setting\config_bak.properties:
language=ru

After modifications don't startup Mixly. Why? Help me.

**Comment by hznupeter** [comment]
Can u give me your ru.js file , i will make it work

**Comment by Enio449** [comment]
it's my ru.js file from blockly\msg\js\company\
[ru.zip](https://github.com/mixly/Mixly_Arduino/files/3494736/ru.zip)

**Comment by hznupeter** [comment]
Thank you , is it based on our newest version?

**Comment by Enio449** [comment]
I have version 0.998

**Comment by hznupeter** [comment]
i've check your ru.js file, it is not the newest version . So the Mixly can't the software cant start .

**Comment by Enio449** [comment]
Where give me newesr version ru.js? My ru.js I'm make from en.js translating.

**Comment by hznupeter** [comment]
because we change a lot after 0.998.

**Comment by Enio449** [comment]
That is, if I install version 1.0 of the beta, will there be no more error?

**Comment by hznupeter** [comment]
Beta😂,maybe small error.

**Comment by Enio449** [comment]
Hi, friend! I'm winner problem) Add ru.properties  In Mixly.jar - don't crush app on startup. 
But new 2 problems:
1) Russian text from ru.properties not correct (page coding UTF-8) "Новый" => "abra-cadabra"
2) On startup app modify setting\config.properties:
language=ru to  en

**Comment by Enio449** [comment]
All right! My decision:

1) Use UTF-8 codes instead text
2) modify setting\config.properties:
autoSetLanguage=false

**Comment by hznupeter** [comment]
Ok. We will fix it in next version.

**Comment by Enio449** [comment]
Thank You!

**Comment by Enio449** [comment]
Do You need files Russian localization for add to project?

**Comment by hznupeter** [comment]
I have add the right ru.js in the repo, we are so glad to hear you help us to translate.
https://github.com/mixly/Mixly_Arduino/blob/master/mixly_arduino/blockly/msg/js/ru.js
in the file ,almost english now.
if you want to debug Mixly, you can open the html files location:mixly_arduino/blockly/apps/mixly/XXXX.html
if you want to use the latest Mixly， you can download from http://116.62.49.166  , and then download the latest repo from github, overwrite files in mixly.zip

**Comment by Enio449** [comment]
Thank You!
