### ISSUE TITLE
针对之前几个我提到的一些问题我自己做了修改，关闭了之前的几个Issues

### ISSUE THREAD

**Issue by human890209** [mixly/Mixly_Arduino#21]
抱歉我不会用Git，我就附上修改过的文件，您可以搜索YANG来快速查询我修改的部分，我保留了原先的所有代码。
名称我只修改了zh-hans和en两种语言，其他语言没修改。

修改内容
1、Wire.begin(address); 此处address是I2C从机的地址，但是I2C从机接收模块上设置的是管脚。我额外增加了一个设置从机地址的模块，取消了接收模块的管脚。
2、添加了一个获取howMany的模块。
3、添加I2C从机读取的模块，类似现在已有的I2C从机接收模块。然后修改Arduino.js 过滤重复的Wire.begin();语句。
4、添加不带Wire.beginTransmission(address);和Wire.endTransmission();的单独的Wire.write(数据);的模块用在读取执行阶段。
5、添加Wire.write(数组，项数)的模块用在读取执行阶段。
6、Array(List)的几个创建模块增加了volatile关键字，找了一下没有看到调用Array的模块，如果以后增加，请记得在调用时在Array之前增加（byte*）因为volatile关键词可能会导致编译出问题。
7、修改了OLED和LED阵列显示时把图标的Array添加PROGMEM关键词，并在调用时使用drawXBMP（）方法替换drawXBM（）方法。
8、给Text增加了一个添加F（）的模块。起到节省内存的作用。
[YANG fix for (10.17) 20191023.zip](https://github.com/mixly/Mixly_Arduino/files/3762579/YANG.fix.for.10.17.20191023.zip)

**Comment by hznupeter** [comment]
感谢您的意见，我已经在增加您提供的部分。如果您可以提交pull request 就更好了，谢谢。

**Comment by human890209** [comment]
嗯，因为我Git不常用，回头我研究学习一下，谢谢。
