### ISSUE TITLE
希望能在Mixly的Wiki中增加添加开发板的指南

### ISSUE THREAD

**Issue by human890209** [mixly/Mixly_Arduino#22]
我想增加lgt8f328p芯片的开发板，但是不知道应该从哪里入手，希望您能在Mixly的Wiki中增加添加开发板的指南。
我手里有几块lgt8f328p的开发板，用了觉得还不错，它是atmega328p的国产替代芯片，价格实惠功能还增强许多，它兼容3.3v和5v并可以在3.3v电压运行在32Mhz，同时A6、A7引脚的功能是完整的。
厂商提供了ArduinoIDE使用的Core和Library等文件，我会使用ArduinoIDE加载这些文件来编译和上传程序。可以直接使用Arduino的328p的程序。
但我不清楚如何在Mixly中添加新的开发板，主要涉及哪些文件。希望您能在Mixly的Wiki中添加1.0版本添加开发板的教程。谢谢！

**Comment by fredqian** [comment]
你让mixly支持的ide支持应该就行了

在2019-10-29 10:04:03，傅骞fredqian@bnu.edu.cn写道：

我想增加lgt8f328p芯片的开发板，但是不知道应该从哪里入手，希望您能在Mixly的Wiki中增加添加开发板的指南。
我手里有几块lgt8f328p的开发板，用了觉得还不错，它是atmega328p的国产替代芯片，价格实惠功能还增强许多，它兼容3.3v和5v并可以在3.3v电压运行在32Mhz，同时A6、A7引脚的功能是完整的。
厂商提供了ArduinoIDE使用的Core和Library等文件，我会使用ArduinoIDE加载这些文件来编译和上传程序。
但我不清楚如何在Mixly中添加新的开发板，主要涉及哪些文件。希望您能在Mixly的Wiki中添加1.0版本添加开发板的教程。谢谢！

**Comment by human890209** [comment]
知道了，我自己研究研究。

**Comment by human890209** [comment]
@fredqian 
你好，给IDE添加硬件的确可以。
因为LGT8F328P还支持DAC。请问如果想添加像ESP32一样的专用模块，应该怎么做？我注意到选中ESP32后界面会刷新，同时ESP32有专门的Html文件来调用和普通Arduino模块不同的js文件并呈现更多的专属模块。这是否需要通过修改mixly的界面java程序才能做到？

**Comment by fredqian** [comment]
不用，自己做一个Index即可，找下index命名的规律，esp32 arduino就是自己的index


在2019-11-04 09:30:00，傅骞fredqian@bnu.edu.cn写道：

@fredqian
你好，给IDE添加硬件的确可以。
因为LGT8F328P还支持DAC。请问如果想添加像ESP32一样的专用模块，应该怎么做？我注意到选中ESP32后界面会刷新，同时ESP32有专门的Html文件来调用和普通Arduino模块不同的js文件并呈现更多的专属模块。这是否需要通过修改mixly的界面java程序才能做到？

**Comment by human890209** [comment]
@fredqian 
好的，的确是这样，好智能啊，赞！
