### ISSUE TITLE
如何在Linux系统下运行Mixly

### ISSUE THREAD

**Issue by 651778286** [mixly/Mixly_Arduino#24]
请问，如何在Linux系统下运行Mixly？

**Comment by fredqian** [comment]
1.0发布，不过只发布64位版，arm不支持，


在2019-12-04 16:26:33，傅骞fredqian@bnu.edu.cn写道：

请问，如何在Linux系统下运行Mixly？

**Comment by hznupeter** [comment]
Linux 版本下载地址http://mixly.org/explore/software?n=100
