### ISSUE TITLE
Port is OK, Cant select board. arduinoPath issue.

### ISSUE THREAD

**Issue by drew345** [mixly/Mixly_Arduino#7]
Looks like nice software, I think the "getting started" needs more instructions though on the arduinoPath variable.

I open the config.properties and replace 
arduinoPath=arduino-1.7.8/
with my arduino path:
arduinoPath=C:\Program Files (x86)\Arduino\

I connect my arduino and I can use the arduino IDE, no problem. Connection is fine (port 6)

BUT, with Mixly, I can select port 6, but cannot select the board, arduino uno. The board selection area is completly black.
When I hit "compile" a message blinks on and off so fast it is impossible to read.
When I hit "upload" I get upload failed.

I am pretty sure the problem is how I have specified the arduinoPath.  I put the directory path to where my arduino.exe file is located. Is that right? But the file path doesn't like like the default arduino-1.7.8/.  How can you even have arduino-1.7.8 ?? The latest release is arduino 1.6.x . 

Can you please check and explain how to enter the arduinoPath variable?
Thank you,
Andrew
rawjmail1@gmail.com

**Comment by fredqian** [comment]
You can download full version in this url.
http://pan.baidu.com/s/1dE3Z6db
